letter_spacing & height TextStyle Property doc
flet-dev/website pull request #239
Opened 2024-02-13 14:19 UTC by ariefendi992

2024-02-13 16:34 UTC, ndonkoHenri requested changes
`height` was not added. You added only `letter_spacing`. Please check, and make the appropriate modifications.

2024-02-13 19:17 UTC, ariefendi992 commented
> `height` was not added. You added only `letter_spacing`. Please check, and make the appropriate modifications.
> 

Indeed, I only added letter_spacing, but in the TextStyle property I couldn't find height documentation for the TextStyle Property, so I took the initiative to add it. because height is already in TextStyle.

2024-02-13 21:18 UTC, ndonkoHenri commented
Ah, @ariefendi992 you are right! The prop exists but is undocumented. Sorry :) 

Last request will be to remove the examples. We don't need to add one for each prop, especially for those easy to understand.

2024-02-14 21:29 UTC, FeodorFitsner approved these changes

2024-02-14 22:26 UTC, merged