Add types to `AlertDialog` control docs
flet-dev/website pull request #308
Opened 2024-06-25 19:25 UTC by taaaf11

2024-06-25 19:25 UTC, taaaf11 commented
@ndonkoHenri kindly review this pr

2024-06-27 04:01 UTC, taaaf11 commented
Ping @ndonkoHenri

2024-06-27 16:05 UTC, ndonkoHenri commented
Did you see my comments?

2024-06-27 16:05 UTC, ndonkoHenri requested changes

2024-06-27 16:05 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +Value is of type `PaddingValue`.
You forgot the link here.

2024-06-27 16:05 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +The (optional) content (of type `Control`) of the dialog is displayed in the center of the dialog in a lighter font. Typically this is a [`Column`](/docs/controls/column) that contains the dialog's [
Similar to the other props, you can instead say below "Value is of type Control.."

2024-06-27 16:05 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +Value is of type `PaddingValue`.
Link here too.

2024-06-27 16:05 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +The value is of type [`PaddingValue`](/docs/reference/types/aliases#paddingvalue).
Can you follow the style we started with: "Value is of type ... [and defaults to]"

2024-06-27 16:05 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +Value is of type `str` or `None`
Lets not mention `None` here, because it is a possible type for (almost) all props.

2024-06-27 16:05 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +The value is of type [`PaddingValue`](/docs/reference/types/aliases#paddingvalue).
Please follow the style as you did with the other props.

2024-06-27 17:02 UTC, taaaf11 commented on docs/controls/alertdialog.md
> +The value is of type [`PaddingValue`](/docs/reference/types/aliases#paddingvalue).
I have followed the style in these lines. No need to change here

2024-06-28 00:02 UTC, taaaf11 commented
Ping @ndonkoHenri

2024-06-28 00:04 UTC, FeodorFitsner commented
@taaaf11 don't spam with pings please. @ndonkoHenri will take a look when available.

2024-06-28 00:12 UTC, taaaf11 commented
Sorry, will take care next time @FeodorFitsner

2024-06-30 11:07 UTC, ndonkoHenri requested changes

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +Value is of type [`Control`].
Missing link?

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +The value of type [`PaddingValue`](/docs/reference/types/aliases#paddingvalue).
"Value is of type..."

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +The value is of type [`PaddingValue`](/docs/reference/types/aliases#paddingvalue).
~The~

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +The value is of type [`PaddingValue`](/docs/reference/types/aliases#paddingvalue).
~The~

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/animatedswitcher.md
> +Value of type `int` defaults to `1000` milliseconds.
is of

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/appbar.md
> +VAlue is of type [`OptionalNumber`](/docs/reference/types/aliases#optionalnumber) and defaults to `1.0`.
Value

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/badge.md
> +The value is of type [`Alignment`](/docs/reference/types/alignment)
~The~

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/badge.md
> +Valeu is of type `bool`.
Typo in Value

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/badge.md
> +Value is of type [`OptionalNumber`](/docs/reference/types/aliases#optionalnumber)  and default value is 16.
"... and defaults to `16`"

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/badge.md
> +Padding value is an instance of [`PaddingValue`](/docs/reference/types/aliases#paddingvalue)
"Value is of type ..."

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/view.md
> +Throttling in milliseconds for `on_scroll` event. Value is of type `int` and defaults to `10`.
Can the typing-highlight be on a new line?

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/view.md
> +Value is of type [`PaddingValue`](/docs/reference/types/aliases#paddingvalue) and defaults to `10`.
"and defaults to `padding.all(10)`"

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/view.md
> +Value is of type [`ScrollMode`](/docs/reference/types/scrollmode) and defaults to `ScrollMode.None`
~" and defaults to `ScrollMode.None`"~

`ScrollMode.None` doesn't exist.

2024-06-30 11:07 UTC, ndonkoHenri commented on docs/controls/webview.md
> +Value is of type `bool`
Please add . to the end of all the sentences

2024-06-30 11:38 UTC, taaaf11 commented on docs/controls/alertdialog.md
> +Value is of type [`Control`].
there is no doc for `Control` in the docs

2024-06-30 11:45 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +Value is of type [`Control`].
Then you can remove the square brackets []

2024-06-30 11:53 UTC, taaaf11 commented on docs/controls/alertdialog.md
> +Value is of type [`Control`].
removed

2024-06-30 13:49 UTC, ndonkoHenri requested changes

2024-06-30 13:49 UTC, ndonkoHenri commented on docs/controls/view.md
> +Value is of type [`ScrollMode`](/docs/reference/types/scrollmode) and defaults to `None`.
If the default is `None`, then we don't mention.

2024-06-30 13:49 UTC, ndonkoHenri commented on docs/controls/view.md
>  Property value is an optional [`ScrollMode`](/docs/reference/types/scrollmode) enum with `None` as default.
I guess we can remove this line.

2024-06-30 13:52 UTC, taaaf11 commented on docs/controls/view.md
>  Property value is an optional [`ScrollMode`](/docs/reference/types/scrollmode) enum with `None` as default.
oh

2024-06-30 16:39 UTC, ndonkoHenri commented on docs/controls/alertdialog.md
> +The value is of type [`PaddingValue`](/docs/reference/types/aliases#paddingvalue).
@taaaf11

2024-07-07 08:27 UTC, ndonkoHenri approved these changes

2024-07-07 08:27 UTC, merged